window.SPINNY_CONTENT = {
  squadName: "TRANSACTION ENRICHMENT INSIGHTS",

  fallbackPeople: [
    "Josh",
    "Alberto",
    "Ana",
    "Valentina",
    "Orestis",
    "Raps",
    "Laurence",
    "Faraz",
    "Sam",
    "Pedro",
    "Adriana",
    "Alex",
    "Natalie",
    "Edgar",
    "Marian",
    "George",
    "Sagar",
    "Demid",
    "Felipe"
  ],

  winnerPhrases: [
    "{name} GOES NOW!!!1!",
    "IT'S {name}'S TURN!",
    "{name} HAS THE FLOOR, UNFORTUNATELY",
    "THE WHEEL DEMANDS {name}",
    "{name} HAS BEEN PIXEL-SELECTED",
    "NEXT UP: {name}!!!",
    "{name} GOT GOT",
    "{name} ENTERS THE STANDUP ZONE",
    "PLEASE WELCOME {name}, I GUESS",
    "{name} IS NOW THE PROBLEM",
    "THE TRIANGLE POINTS AT {name}",
    "{name} HAS BEEN CHOSEN BY BAD MATH",
    "{name} IS THE CURRENT VICTIM",
    "OVER TO {name}",
    "{name} GOES BEFORE THE COUNCIL",
    "THE COMPUTER SAYS {name}",
    "{name} WAS INSIDE THE WHEEL ALL ALONG",
    "{name} GETS THE MICROPHONE",
    "LOOKS LIKE {name} TIME",
    "{name} HAS TO DO WORDS",
    "{name} IS UP, PROBABLY",
    "THE PIXELS HAVE RATIFIED {name}",
    "{name} WON THE TINY BAD PRIZE",
    "{name} TAKES THE NEXT LAP",
    "ALL SIGNS POINT TO {name}",
    "{name} HAS BEEN ELECTED BY NO ONE",
    "{name} MUST SPEAK NOW",
    "{name} IS LIVE ON CHANNEL WHEEL",
    "THE POINTER BETRAYS {name}",
    "{name} RECEIVES THE CURSED BATON",
    "IT LANDED ON {name}, SOMEHOW",
    "{name} IS THE NEXT HUMAN",
    "THE WHEEL HAS A NOTE: {name}",
    "CURRENTLY HAPPENING: {name}",
    "{name} HAS BEEN LOUDLY INDICATED",
    "MAKE WAY FOR {name}",
    "{name} IS THE STANDUP ITEM",
    "THE BAD CIRCLE WANTS {name}",
    "{name} GETS THE NEXT TURN",
    "{name} IS UP NEXT!!!",
    "THE MACHINE CHOOSES {name}",
    "{name} HAS BEEN SORTED TO NOW",
    "{name}, REPORT TO THE WHEEL",
    "THE WHEEL VIBES SAY {name}",
    "{name} IS THIS MOMENT'S PERSON",
    "{name} GOES NOW OR ELSE",
    "I REGRET TO ANNOUNCE {name}",
    "{name} HAS ENTERED TURN MODE",
    "THE ANSWER IS {name}",
    "BACKFILL COMPLETE: {name}",
    "{name} IS FLOW_TYPE=LIVE",
    "{name} HAS FLOW_TYPE=BACKFILL ENERGY",
    "THE DLQ HAS CHOSEN {name}",
    "{name} IS BELOW TWO MESSAGES PER SECOND",
    "OFFSET LAG POINTS AT {name}",
    "{name} PASSED THE B_SIDE GATE",
    "THE GOLDEN SET HAS MAPPED {name}",
    "{name} BEATS THE CHALLENGER MODEL",
    "PR DEPLOYMENT SUMMONS {name}",
    "{name} HAS SICK-POD DETECTOR VIBES",
    "SWARMIA HAS NOISILY SELECTED {name}",
    "RUNBOOK SAYS: {name} NOW",
    "CARD-ACCOUNT LINKAGE REQUESTS {name}",
    "THE JUNE 15 BACKFILL CLOCK SELECTS {name}",
    "{name} IS THE PROMETHEUS LABEL TODAY"
  ],

  finalWheelLabels: [
    "and finally, {name}",
    "last one: {name}",
    "closing ceremony: {name}",
    "inevitably, {name}",
    "final checkpoint: {name}",
    "last b_side human: {name}",
    "the final flow_type is {name}",
    "only {name} remains in main"
  ],

  sendoffMessages: [
    "everyone now have a nice day",
    "time to do the things",
    "bye bye see everyone later",
    "standup has left the building",
    "go forth and enrich transactions",
    "the circle is empty now",
    "please return to your tabs",
    "meeting concluded by bad geometry",
    "that was legally a standup",
    "the wheel releases you",
    "all humans have been processed",
    "nothing left but Jira",
    "thank you for attending the rectangle",
    "you may now resume having problems",
    "see everyone in the next ritual",
    "run along now",
    "the pixels say goodbye",
    "back to the important nonsense",
    "the agenda has evaporated",
    "standup complete, emotionally speaking",
    "go make the graphs less weird",
    "the wheel is going for a lie down",
    "please enjoy the rest of capitalism",
    "all turns have been consumed",
    "return to prod with caution",
    "the ceremony is over",
    "have a productive-ish day",
    "goodbye from the bad circle",
    "go do one small useful thing",
    "the squad may now disperse",
    "all checkpoints have been finalized",
    "the offset lag is somebody else's tab now",
    "resume pretending Coralogix is fine",
    "the backfill scoreboard has gone quiet",
    "please file your remaining thoughts under TBD",
    "meeting emitted zero DLQ messages"
  ],

  squadLore: [
    "TRANSACTION ENRICHMENT INSIGHTS",
    "BACKFILL BY JUNE 15",
    "TWO CSVS ENTER",
    "ASYNC_ENRICHMENT NOT ASYNC_ENRICHMENT_TEST",
    "B_SIDE OR CANCELLED",
    "CHECKPOINT CANCELLED WITH REASON",
    "FLOW_TYPE=LIVE",
    "FLOW_TYPE=BACKFILL",
    "LIVE HEALTH SCORE SAYS NO",
    "BACKFILL SCOREBOARD ONLY SLACKS",
    "DLQ DEPTH MUST BE ZERO",
    "MAIN DLQ HAS MESSAGES",
    "NON-MAIN PR DLQ HAS MESSAGES",
    "OFFSET LAG NO DOWNWARD TREND",
    "ONE MILLION MESSAGES AND A FLAT SLOPE",
    "LOW THROUGHPUT BELOW TWO MSG/S",
    "4XX 5XX P3 PARADE",
    "P2 IF SENSITIVE ENOUGH",
    "SICK-POD DETECTOR",
    "PARTITION-SKEW WATCH",
    "STDDEV OVER AVG LOOKS JUDGY",
    "MIN OVER AVG NEEDS A DASHBOARD",
    "READONLY_ASYNC_ENRICHMENT_REQUESTED_AT",
    "TRANSACTIONS_ASYNC_ENRICHMENT_INTERNAL_LATENCY",
    "PR DEPLOYS ARE NOISY",
    "SWARMIA IS VERY NOISY",
    "GOLDEN SET CP ID MAPPING",
    "AUXILIARY GOLDEN SET COMPLETED",
    "CLEO COUNTERPARTY EXCLUDES EMPLOYEES",
    "LLMAAJ PRECISION SNACK",
    "CARD-ACCOUNT LINKAGE WANTS CLEO CP",
    "CATEGORY TAXONOMY V2 FINAL-ISH",
    "JIT APP-OPEN BACKFILL",
    "ACTIVE EWA PRIORITY BUCKET",
    "AUTOPILOT WAITLIST DECOUPLING",
    "ODC V11 NEEDS ENRICHED HISTORY",
    "PR 4319 DEPLOYMENT SUMMARY",
    "DESTROY IS NOT WORKING",
    "GPU SHORTAGE AGAIN",
    "ORPHAN PR-BASED CONSUMERS",
    "RUNBOOK BASE IS THERE",
    "HIGH RETRY RATE FROM RAW TOPIC",
    "TOO MANY LOG ERRORS METRIC TBD",
    "PROMETHEUS SPELLCHECK PENDING",
    "PLAID INITIAL UPDATE TIMER",
    "FRESHNESS VS LATENCY DEBATE",
    "BACKFILL HEADER GOES TO THE BACK",
    "PRIORITY EVENTS CUT THE QUEUE",
    "APP OPENS, USERS APPEAR",
    "CANNOT ONBOARD BUCKET",
    "PER-POD THROUGHPUT DRAMA",
    "BATCH_TRANSACTION_ENRICHMENT_DURATION",
    "MESSAGING_PROCESS_MESSAGES_TOTAL",
    "CORALOGIX HAS OPINIONS",
    "GRAFANA PANEL KNOWS THINGS",
    "INCIDENT.IO HAS BEEN INFORMED",
    "PHANTOMMODE TRUE, MAYBE",
    "ONWARDS",
    "NICE",
    "AMAZE",
    "THAT'S BRUCE"
  ],

  targetedAds: [
    {
      eyebrow: "Sponsored",
      target: "Josh",
      headline: "Cleo counterparty precision looking too knowable?",
      body: "LLMaaj Lens filters employee transactions, feeds card-account linkage, and returns a confidence score with suspicious posture.",
      product: "Counterparty Oracle Pro",
      cta: "Score the Cleo bits",
      lore: "CLEO COUNTERPARTY EVAL EXCLUDES EMPLOYEES"
    },
    {
      eyebrow: "Promoted",
      target: "Alberto",
      headline: "Need it statistically the same, not identical?",
      body: "BaselineBuddy compares PR 4319 to prod, prints a green-ish rectangle, and whispers that parity is a social construct.",
      product: "BaselineBuddy",
      cta: "Open challenger model",
      lore: "STATISTICALLY SAME, NOT IDENTICAL"
    },
    {
      eyebrow: "Recommended",
      target: "Ana",
      headline: "PR endpoint needed for evaluation again?",
      body: "FlyteFindr checks the VPN, finds the dashboard link, and asks MLflow which domain it believes in today.",
      product: "FlyteFindr",
      cta: "Locate dashboard",
      lore: "PR ENDPOINT FOR EVALUATION"
    },
    {
      eyebrow: "Sponsored result",
      target: "Valentina",
      headline: "Golden-set CP IDs refusing to map themselves?",
      body: "OracleLabel Studio lines up auxiliary labels, Cleo counterparties, and one spreadsheet that insists it is final.",
      product: "OracleLabel Studio",
      cta: "Map the CPs",
      lore: "GOLDEN SET CP ID MAPPING"
    },
    {
      eyebrow: "Sponsored",
      target: "Orestis",
      headline: "Call link hiding behind product terminology?",
      body: "Bruce Locator finds the Zoom, names the meeting, and confirms the ontology is probably just Bruce.",
      product: "Bruce Locator",
      cta: "Find the link",
      lore: "THAT'S BRUCE"
    },
    {
      eyebrow: "Promoted",
      target: "Raps",
      headline: "Unconnected account detection wants a ruling?",
      body: "LinkageJudge runs TE2 through the card-account maze and returns a work-safe shrug with trace IDs.",
      product: "LinkageJudge",
      cta: "Judge the linkage",
      lore: "UNCONNECTED ACCOUNT DETECTION"
    },
    {
      eyebrow: "Recommended",
      target: "Laurence",
      headline: "Alerting bits escaping the post-mortem?",
      body: "CeremonyCompressor converts incident residue into runbook sections, Jira fog, and one meeting that might be useful.",
      product: "WaysOfWorking Turbo",
      cta: "Tighten ceremony",
      lore: "RUNBOOK BASE IS THERE"
    },
    {
      eyebrow: "Sponsored result",
      target: "Faraz",
      headline: "Offset lag alert still too interesting?",
      body: "AlertSmith adds low range, long range, low throughput, retries, and a Swarmia mute button nobody can find.",
      product: "AlertSmith",
      cta: "Tune the threshold",
      lore: "OFFSET LAG ALERT NEEDS LOW AND LONG RANGE"
    },
    {
      eyebrow: "Recommended",
      target: "Sam",
      headline: "Need a tiny backfill before the real one notices?",
      body: "PartitionFiller requests 1k users, checks the async gate, and writes down which DLQ topic was missing this time.",
      product: "PartitionFiller",
      cta: "Request 1k users",
      lore: "REQUESTED 1K BACKFILL STARTING NOW"
    },
    {
      eyebrow: "Sponsored",
      target: "Pedro",
      headline: "Parity check or p95 latency?",
      body: "PerfProbe compares challenger models against prod and politely asks what kind of performance you meant.",
      product: "PR Evaluation Tool",
      cta: "Measure p95",
      lore: "P95 LATENCY IS NOT THE WHOLE PARITY CHECK"
    },
    {
      eyebrow: "Sponsored",
      target: "Adriana",
      headline: "Deploy freeze, DLQ cleanup, and avro schemas?",
      body: "AvroTherapy removes custom DLQs, protects the pods, and persuades `max_decimal` to stop being avant-garde.",
      product: "SchemaSentry",
      cta: "Validate my decimal",
      lore: "CUSTOM DLQ TOPIC REMOVED"
    },
    {
      eyebrow: "Promoted",
      target: "Alex",
      headline: "Backfill priority buckets multiplying?",
      body: "CohortBouncer ranks Active EWA, Autopilot waitlist, app-open JIT, and the vast territory called Other.",
      product: "CohortBouncer",
      cta: "Rank the buckets",
      lore: "ACTIVE EWA PRIORITY BUCKET"
    },
    {
      eyebrow: "Promoted",
      target: "Natalie",
      headline: "Precision and recall swapped again?",
      body: "MetricLibrarian shelves freshness, completeness, drift, and fallback rate before the health score turns yellow.",
      product: "MetricLibrarian",
      cta: "File the metric",
      lore: "ML QUALITY SLO SAME FOR BACKFILL"
    },
    {
      eyebrow: "Sponsored",
      target: "Edgar",
      headline: "PR deployments making the channel crunchy?",
      body: "VariantWrangler groups by namespace, service, and variant so main and pr-XXXX can argue separately.",
      product: "VariantWrangler",
      cta: "Split the variants",
      lore: "MAIN AND PR DEPLOYS TRACKED SEPARATELY"
    },
    {
      eyebrow: "Recommended",
      target: "Marian",
      headline: "Newsletter says endpoint. But endpoint?",
      body: "DigestDecoder removes duplicate status words, decodes prod traffic, and ships the ML weekly with fewer riddles.",
      product: "DigestDecoder",
      cta: "Decode endpoint",
      lore: "ML DIGEST ENDPOINT MIGHT MEAN PROD TRAFFIC"
    },
    {
      eyebrow: "Sponsored",
      target: "George",
      headline: "Golden set mapped to CP IDs yet?",
      body: "EntityMatcher Deluxe researches the maybe-matches, blanks the bad ones, and charges by auxiliary spreadsheet.",
      product: "EntityMatcher Deluxe",
      cta: "Match the entities",
      lore: "AUXILIARY GOLDEN SET COMPLETED"
    },
    {
      eyebrow: "Recommended",
      target: "Sagar",
      headline: "Need the smallest possible backfill snack?",
      body: "CanaryBatch asks for 1k users, watches tx/sec fall over itself, and reports that low double digits are technically digits.",
      product: "CanaryBatch",
      cta: "Start small",
      lore: "TX PER SEC IS NOT WHAT IT USED TO BE"
    },
    {
      eyebrow: "Sponsored result",
      target: "Demid",
      headline: "Blocked on e2e latency metric?",
      body: "PassThrough Butler adds `readonly_async_enrichment_requested_at`, then asks the async enricher to please carry the parcel.",
      product: "PassThrough Butler",
      cta: "Pass the field",
      lore: "READONLY ASYNC ENRICHMENT REQUESTED AT"
    },
    {
      eyebrow: "Promoted",
      target: "Felipe",
      headline: "Tracing raw_transaction back to Plaid?",
      body: "TopicTimeMachine follows raw events upstream, checks the runbook, and refuses to merge backend DLQ folklore with MLOps DLQ folklore.",
      product: "TopicTimeMachine",
      cta: "Trace the event",
      lore: "RAW_TRANSACTION BACK TO PLAID?"
    }
  ],

  winnerBadges: [
    "LEGAL PICK",
    "PROD CERTIFIED",
    "DLQ ZERO",
    "B_SIDE OK",
    "FLOW_TYPE LIVE",
    "FLOW_TYPE BACKFILL",
    "NO REFUNDS",
    "PLAIDISH",
    "RUNBOOKED",
    "SLO-ISH",
    "PR-XXXX",
    "SWARMIA NOISE"
  ],

  sendoffStamps: [
    "ALL DONE",
    "ROUND COMPLETE",
    "SHIP IT???",
    "CEREMONY CLOSED",
    "GOODBYE MODE",
    "NO MORE NAMES",
    "DLQ CLEAR",
    "BACKFILL QUEUED",
    "HEALTH SCORE GREEN-ISH"
  ],

  sendoffSubtitles: [
    "click anywhere to return to whatever this was",
    "final modal acknowledged by no committee",
    "no further wheel events remain",
    "the standup-shaped object is complete",
    "reset round if you need more ceremony",
    "no checkpoints were harmed by this modal",
    "flow_type labels have been emotionally reconciled",
    "Coralogix will now resume having opinions"
  ],

  crashMessages: [
    "Fatal ceremony error at 0xWHEEL",
    "",
    "Cause: everyone has spoken and the application cannot cope.",
    "Recovered names: 0",
    "Pointer integrity: emotionally unavailable",
    "Suggested action: pretend this browser tab is normal.",
    "",
    "TRANSACTION_ENRICHMENT_INSIGHTS_STACKTRACE:",
    "  at BackfillScoreboard.turnGreenish()",
    "  at DlqDepth.assertZero()",
    "  at SwarmiaNotification.beQuiet()",
    "  at MeetingFinished.butTooDramatically()",
    "  at Wheel.exe: line absolutely not found"
  ]
};
