window.SPINNY_CONTENT = {
  squadName: "TX ENRICHMENT & INSIGHTS",

  fallbackPeople: [
    "Josh",
    "Alberto",
    "Ana",
    "Valentina",
    "Orestis",
    "Raps",
    "Laurence",
    "Faraz",
    "Sam",
    "Pedro",
    "Adriana",
    "Alex",
    "Natalie",
    "Edgar",
    "Marian",
    "George",
    "Sagar",
    "Demid",
    "Felipe"
  ],

  winnerPhrases: [
    "{name} GOES NOW!!!1!",
    "IT'S {name}'S TURN!",
    "THE WHEEL DEMANDS {name}",
    "{name} HAS BEEN PIXEL-SELECTED",
    "NEXT UP: {name}!!!",
    "{name} ENTERS THE STANDUP ZONE",
    "THE TRIANGLE POINTS AT {name}",
    "THE COMPUTER SAYS {name}",
    "{name} HAS TO DO WORDS",
    "THE BAD CIRCLE WANTS {name}",
    "THE HIGH PRIORITY LANE REQUESTS {name}",
    "{name} ARRIVED IN UNDER 49 SECONDS",
    "THE 1% US ON-RAMP SELECTS {name}",
    "ALL UK USERS, PLUS {name}",
    "THE DEDICATED CHECKPOINT RELEASES {name}",
    "THE RTD HAS GROUPED {name}",
    "UIC AS A SHELL PRESENTS {name}",
    "POINT-IN-TIME SEMANTICS FOUND {name}",
    "THE C COMPILER APPROVES {name}",
    "BYT5 EMITTED ONE COUNTERPARTY: {name}",
    "255 FILES LATER, {name}",
    "CIRCLECI THINKS {name} IS MERGEABLE-ISH",
    "NULL RATE DRIFT POINTS AT {name}",
    "THE BACKFILL WAS ONLY 60K, SO {name}",
    "DB SPANS ARE UP; SEND {name}",
    "OFFSET LAG MAY BE {name}",
    "THE THREE PRIORITY QUEUES AGREE ON {name}",
    "INVOKED_BY={name}",
    "THE 48 ORPHAN ENDPOINTS ELECT {name}",
    "CORALOGIX PROCESSED ENOUGH TO CHOOSE {name}",
    "THE GAUGE SHOWS THE LAST HOUR OF {name}",
    "RUNBOOK SAYS {name} IS FIRST RESPONDER",
    "DAG OBSERVABILITY DISCOVERED {name}",
    "THE GOLDEN SET GIVES {name} 85%",
    "THIRTY-NINE DAY BUCKETS CONVERGE ON {name}",
    "COUNTERPARTY ACCURACY IS 87.3%; {name} ACCURACY PENDING",
    "BACKFILL COMPLETE: 2.2M USERS AND {name}",
    "RECALL IS 92%; PRECISION SELECTS {name}",
    "THE DAILY PULSE NEEDS {name} BY TOMORROW",
    "FIVE PANDAS MERGES PRODUCED {name}",
    "THE BOUNDARY NOTIFIER FOUND {name}",
    "THE MODEL POPULATION CONTAINS {name}",
    "TRAFFIC MIRRORING REFLECTS {name}",
    "THE CODEOWNERS FILE SUMMONS {name}",
    "THE COUNT DASH CONFIRMS {name}",
    "THE SIDEKIQ QUEUE RELEASES {name}",
    "OPERATIONAL MATURITY HAS ASSIGNED {name}",
    "THE DASHBOARD LIMIT IS NOW {name}",
    "THE WHEEL FOUND A KNOWN CALLER: {name}",
    "THE LOW PRIORITY LANE CAN WAIT FOR {name}",
    "THE SERVICE WASN'T RUNNING, BUT {name} IS",
    "THE POINT-IN-TIME SILVER LAYER REMEMBERS {name}"
  ],

  finalWheelLabels: [
    "and finally, {name}",
    "last one in the high priority lane: {name}",
    "dedicated checkpoint: {name}",
    "the final RTD group is {name}",
    "only {name} survived the 60k backfill",
    "final caller identified as {name}",
    "the last non-null counterparty is {name}",
    "UIC shell contains {name}"
  ],

  sendoffMessages: [
    "everyone now have a nice day",
    "the 1% cohort may now expand",
    "all 2.2m users have left the wheel",
    "the dedicated checkpoint has fired",
    "RTD has grouped the entire meeting",
    "UIC may now remain a shell",
    "CircleCI reports the ceremony mergeable-ish",
    "the C compiler has gone home",
    "null counterparty rate back to normal-ish",
    "the three priority queues are empty",
    "DB spans can stop climbing now",
    "offset lag was a red herring",
    "Coralogix has reached its processing limit",
    "all 48 orphan endpoints have spoken",
    "first responders may close the runbook",
    "the gauge returns to last-hour mode",
    "the daily pulse resumes tomorrow",
    "all invoked_by values accounted for",
    "the 39 day buckets have dispersed",
    "the golden set applauds at 85%",
    "point-in-time semantics will remember this",
    "the backfill was only 60k",
    "please return to your dashboards",
    "meeting concluded under 30 seconds eventually",
    "standup has moved to the low priority lane",
    "all counterparties are non-null",
    "the wheel releases the new engineering manager",
    "no more names, only DB spans",
    "the notifier found no boundary violations",
    "that was legally operational maturity"
  ],

  squadLore: [
    "TX ENRICHMENT & INSIGHTS",
    "HIGH PRIORITY LANE",
    "NEW USER ENRICHMENT UNDER 30S",
    "CURRENTLY ABOUT 49 SECONDS",
    "ONE TO FOUR MINUTES, USUALLY",
    "ALL UK USERS ARE ELIGIBLE",
    "ONE PERCENT US ON-RAMP",
    "DEDICATED HISTORICAL CHECKPOINT",
    "LOW PRIORITY MEANS BIG BACKFILL",
    "BACKFILL 2.2M OF 2.2M",
    "ONLY 60K USERS THIS TIME",
    "THREE PRIORITY EVENT TOPICS",
    "LOW MEDIUM HIGH",
    "SILENTLY DROPPED TRANSACTIONS",
    "MORNING RETRY JOB KNOWS",
    "DB SPANS KEEP GOING UP",
    "P95 LATENCY?",
    "OFFSET LAG OR RED HERRING",
    "RTD GROUPS IT FOR FREE",
    "UIC AS A SHELL",
    "ONE SERVICE BY T1 2027",
    "POINT-IN-TIME SILVER LAYER",
    "DATA GATEWAY REMEMBERS",
    "FIVE PANDAS MERGES LATER",
    "DAILY PULSE WANTS FRESH RECURRING",
    "RECURRING FLAG MAY DISAGREE",
    "BYT5 NEEDS A C LIBRARY",
    "NULL COUNTERPARTIES EVERYWHERE",
    "255 FILES PR",
    "CIRCLECI SAYS NOT MERGEABLE",
    "PR DEPLOY PERFECT, MASTER DEAD",
    "DRIFT ALERTING WOULD NOTICE",
    "MINIMUM COUNTERPARTY SCORE",
    "FIRST RESPONDER AGENT",
    "RUNBOOKS ARE IN PLACE",
    "DAG OBSERVABILITY PLEASE",
    "BOUNDARY VIOLATION NOTIFIER",
    "48 ENABLED ENDPOINTS, NO KNOWN CALLER",
    "INVOKED_BY OR REQUEST HEADER",
    "WHO IS CALLING THE SERVICE",
    "CORALOGIX PROCESSING LIMIT",
    "GAUGES WERE ALWAYS LAST HOUR",
    "LATENCY HISTOGRAM TOO COMPLEX",
    "87.3% COUNTERPARTY ACCURACY",
    "73.4% DETAILED CATEGORY ACCURACY",
    "92% UNCONNECTED ACCOUNT RECALL",
    "85% GOLDEN SET WITH OPTIMISED PROMPTS",
    "1.5K HUMAN-LABELLED TRANSACTIONS",
    "THIRTY-NINE DAY BUCKETS",
    "UK TRAFFIC MIRRORING: 43 USERS",
    "GROUPED COUNTERPARTY TABLE NAMING",
    "CODEOWNERS WOULD LIKE A REVIEW",
    "FDIC NCUA ALIAS LOOKUP",
    "THE SERVICE CAN'T ERROR IF IT ISN'T RUNNING",
    "CLEO IS NEVER BORING",
    "OPERATIONAL MATURITY ACHIEVED-ISH"
  ],

  targetedAds: [
    {
      eyebrow: "Sponsored",
      target: "Josh",
      headline: "CircleCI questioning your mergeable PR again?",
      body: "Retry From Start Pro rebases to master, gets the same error, and promises the PR deploy really did work before lunch.",
      product: "Mergeability Reassurance Cloud",
      cta: "Retry from start",
      lore: "PR DEPLOY PERFECT, MASTER DISAPPOINTING"
    },
    {
      eyebrow: "Promoted",
      target: "Alberto",
      headline: "ByT5 compiling without a C compiler?",
      body: "HeaderHero adds one library, 255 files, two approvals, and a decade of well-earned relaxation to every image.",
      product: "HeaderHero Enterprise",
      cta: "Install the headers",
      lore: "NULL COUNTERPARTIES NEED A C LIBRARY"
    },
    {
      eyebrow: "Recommended",
      target: "Ana",
      headline: "Payday confidence spread across 39 buckets?",
      body: "Threshold Translator explains why 0.1 is strict now, then sends the remaining users to a fallback date with dignity.",
      product: "Threshold Translator v4",
      cta: "Compare nothing",
      lore: "THRESHOLDS ARE NOT COMPARABLE"
    },
    {
      eyebrow: "Sponsored result",
      target: "Valentina",
      headline: "Need 85% accuracy but Bedrock says no?",
      body: "GoldenHaiku optimises GPT and Opus prompts on 1.5k labelled transactions while Terraform locates one missing permission.",
      product: "GoldenHaiku Airflow Edition",
      cta: "Invoke the model",
      lore: "85% AFTER PROMPT OPTIMISATION"
    },
    {
      eyebrow: "Sponsored",
      target: "Orestis",
      headline: "Income-tag latency hiding behind five merges?",
      body: "PandasPeriscope separates boolean masks, the actual classifier call, dataframe construction, and every merge wearing one latency trench coat.",
      product: "PandasPeriscope",
      cta: "Profile the coat",
      lore: "THE ALERT MEASURES MORE THAN THE CALL"
    },
    {
      eyebrow: "Promoted",
      target: "Raps",
      headline: "UK enrolled but the US still at one percent?",
      body: "OnRamp-O-Matic adds a dedicated checkpoint, invites new US users carefully, and promises to remember the backfill later.",
      product: "TE2 OnRamp-O-Matic",
      cta: "Enroll one percent",
      lore: "ALL UK, ONE PERCENT US"
    },
    {
      eyebrow: "Recommended",
      target: "Laurence",
      headline: "Offset lag pointing at the wrong backfill?",
      body: "RedHerring Radar opens Grafana, Coralogix, and the postmortem simultaneously, then labels the least convincing chart probably relevant.",
      product: "RedHerring Radar",
      cta: "Observe indirectly",
      lore: "MAYBE A RED HERRING"
    },
    {
      eyebrow: "Sponsored result",
      target: "Faraz",
      headline: "Runbooks present but DAG observability absent?",
      body: "FirstResponder Agent adds classifier metrics, alert links, GitHub teams, and a polite question about whether this is critical.",
      product: "FirstResponder Agent Pro",
      cta: "Find more clues",
      lore: "DAG OBSERVABILITY PLEASE"
    },
    {
      eyebrow: "Recommended",
      target: "Sam",
      headline: "New counterparty table insufficiently explicit?",
      body: "NameLengthener maps the embedder, enricher, consumers, nightly grouping, and one generated_counterparty_relation_grouped_counterparty.",
      product: "NameLengthener",
      cta: "Add another noun",
      lore: "THE DEVIL IS IN THE TABLE NAME"
    },
    {
      eyebrow: "Sponsored",
      target: "Pedro",
      headline: "Five-fold DB spans with unclear ownership?",
      body: "EscalationRouter distinguishes GitHub teams from first responders, tags the whole pillar, and adds the instruction to the runbook.",
      product: "EscalationRouter",
      cta: "Notify the right group",
      lore: "GITHUB TEAM IS NOT THE FR GROUP"
    },
    {
      eyebrow: "Sponsored",
      target: "Adriana",
      headline: "Only 60k users melting the database?",
      body: "BackfillAlibi watches all three priority queues, reconnects RTD, and asks why the same workload suddenly has opinions.",
      product: "BackfillAlibi",
      cta: "Check DB spans",
      lore: "WE HAVE RUN BIGGER BACKFILLS"
    },
    {
      eyebrow: "Promoted",
      target: "Alex",
      headline: "Unconnected-account cohorts need one more cut?",
      body: "CohortCarpenter turns 9.1%, 19.6%, connected checking, and no connected checking into a Count table beneath the original table.",
      product: "CohortCarpenter",
      cta: "Add breakdown",
      lore: "30.5K USERS IN THIS COHORT"
    },
    {
      eyebrow: "Promoted",
      target: "Natalie",
      headline: "Traffic mirror found only 43 UK users?",
      body: "AccruedIncome Scope checks PR-4730, the employee overlay, GB coverage, and whether the backend workaround may now retire.",
      product: "AccruedIncome Scope",
      cta: "Inspect the mirror",
      lore: "UK COVERAGE CAME OUT VERY LOW"
    },
    {
      eyebrow: "Sponsored",
      target: "Edgar",
      headline: "Transformers insufficiently mathematical?",
      body: "AttentionFramework converts the journal-club paper into presentation notes and guarantees at least one diagram nobody will question aloud.",
      product: "AttentionFramework",
      cta: "Present the theorem",
      lore: "A MATHEMATICAL FRAMEWORK OF TRANSFORMERS"
    },
    {
      eyebrow: "Recommended",
      target: "Marian",
      headline: "Provider predictor wants a credit-union alias?",
      body: "AliasBridge combines FDIC, NCUA, entity_type, CODEOWNERS, and one humble approval into a feature with plausible coverage.",
      product: "AliasBridge",
      cta: "Bridge the projects",
      lore: "FDIC NCUA ALIAS LOOKUP"
    },
    {
      eyebrow: "Sponsored",
      target: "George",
      headline: "Weekly OKR update running out of percentages?",
      body: "Scoreboard Deluxe celebrates 87.3% counterparty accuracy, 73.4% detailed category accuracy, 92% recall, and 2.2m users backfilled.",
      product: "Scoreboard Deluxe",
      cta: "Ship week twelve",
      lore: "BACKFILL 100% OF COHORT"
    },
    {
      eyebrow: "Recommended",
      target: "Sagar",
      headline: "Under-30-second enrichment currently taking 49?",
      body: "LatencySLO Maybe builds a high-priority lane, declines to promise a number, and investigates how quickly eventually can happen.",
      product: "LatencySLO Maybe",
      cta: "Target under 30",
      lore: "CURRENTLY ABOUT 49 SECONDS"
    },
    {
      eyebrow: "Sponsored result",
      target: "Demid",
      headline: "One event topic became three overnight?",
      body: "PriorityTopic Sorter routes low, medium, and high cohorts, respects the June 1 cutoff, and excludes anything already enriched elsewhere.",
      product: "PriorityTopic Sorter",
      cta: "Use not_enriched",
      lore: "LOW MEDIUM HIGH TOPICS"
    },
    {
      eyebrow: "Promoted",
      target: "Felipe",
      headline: "Dashboard limitation in need of management?",
      body: "NewEM Console displays the Coralogix limits, postpones the RFC until it matters, and confirms nothing can error while it is not running.",
      product: "NewEM Console",
      cta: "Display limitations",
      lore: "IT CAN'T ERROR IF IT ISN'T RUNNING"
    }
  ],

  winnerBadges: [
    "HIGH PRIORITY",
    "UNDER 30S-ISH",
    "CHECKPOINTED",
    "RTD GROUPED",
    "UIC SHELL",
    "C LIBRARY ADDED",
    "COUNTERPARTY NON-NULL",
    "DRIFT ALERTED",
    "INVOKED_BY KNOWN",
    "RUNBOOKED",
    "GAUGE LIMITED",
    "2.2M DONE"
  ],

  sendoffStamps: [
    "ALL DONE",
    "ROUND COMPLETE",
    "CHECKPOINT FIRED",
    "RTD CONSOLIDATED",
    "NO MORE NAMES",
    "THREE QUEUES CLEAR",
    "NULL RATE NORMAL",
    "BACKFILL 100%",
    "MERGEABLE-ISH"
  ],

  sendoffSubtitles: [
    "click anywhere to return to the high priority lane",
    "no further wheel events remain in any queue",
    "the 1% cohort has been emotionally enrolled",
    "all callers now have an invoked_by field",
    "the gauge is showing exactly one hour of closure",
    "reset round if the dedicated checkpoint misfires",
    "the RTD has grouped this meeting for free",
    "CircleCI may disagree with this outcome"
  ],

  crashMessages: [
    "Fatal ceremony error at 0xWHEEL",
    "",
    "Cause: everyone has spoken and the application cannot cope.",
    "Recovered names: 0",
    "Priority lane: LOW",
    "Counterparty null rate: 100%",
    "Dedicated checkpoint: pending",
    "Suggested action: retry from start.",
    "",
    "TX_ENRICHMENT_INSIGHTS_STACKTRACE:",
    "  at CircleCI.assertMergeable()",
    "  at ByT5.compileWithCLibrary()",
    "  at RtdGroup.mergeFiveDataFrames()",
    "  at CoralogixGauge.exceedProcessingLimit()",
    "  at MeetingFinished.butTooDramatically()",
    "  at Wheel.exe: line absolutely not found"
  ]
};
